services:
  udp2raw:
    build:
      context: .
      dockerfile: Dockerfile.udp2raw
    image: udp2raw-local:latest
    container_name: udp2raw-client
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: >
      udp2raw -c -l 127.0.0.1:${SERVER_UDP_PORT} -r ${SERVERURL}:${FAKETCP_PORT} -k ${UDP2RAW_KEY} --raw-mode faketcp --cipher-mode aes128cbc --auth-mode simple --fix-gro -a
    restart: unless-stopped

  wg-client:
    image: linuxserver/wireguard:latest
    container_name: wg-client
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config:/config
    depends_on:
      - udp2raw
    restart: unless-stopped
